theme: jekyll-theme-cayman
title: sttp.dotnetapi
description: Streaming Telemetry Transport Protocol (STTP) .NET API
github:
  repository_name: sttp.dotnetapi
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji